"""HUD generator acceptance suite for HUDLINE.

Run from the repository root:
    python tools/test_generate_hud.py

Acceptance criteria:
1. Both generated ability rows sit at y=-35; exactly three frames are gated to slot_count 3
   and exactly four are gated to slot_count 4.
2. One centered feedback text element reads legendcraft_feedback_line at y=-47 and scale 0.5.
3. The tile bottom stays 5px above the vanilla held-item-name lane used by the compositor.
4. Checked-in layout YAML and the cross-repo placeholder manifest equal generator truth.

First RED (2026-08-30, before generator implementation): four tests ran and all four failed.
The checked-in manifest differed because shield_current/shield_max were absent; generated frame
y values were {-25}, expected {-45}; the feedback element count was 0, expected 1; and native-lane
clearance was -5px, expected 15px.

Re-ruled 2026-09-05 (owner, after seeing hoist 20 and 10 in client): SKILL_ROW_HOIST_PX drops
20 -> 10, moving the ability rows and the feedback line down 10px together and narrowing the
held-item-lane clearance 15px -> 5px. Criteria 1-3 carry the new ruled values; the assertions
themselves are unchanged, only the numbers they pin.

HUD-AIR criteria (added 2026-09-05; PR #7 blanked the vanilla oxygen bubbles, which render in
the vanilla armor lane on top of the stat block, and left drowning with no read at all):
5. The stat block carries an air element -- channel, native fill, icon -- and all three parts
   are hidden at full air by the same gate. A part that is not gated is a part that draws
   while you are breathing.
6. That element rides the XP row and stays inside its left third, so it clears the centred
   level numeral and the right-aligned XP numerals on the rail it draws over.
7. The fill is BetterHud's native `air` listener and the gate is BetterHud's own `air` /
   `max_air` built-ins, so no part of this element reaches LegendCraft-Classes -- it cannot go
   dark the way a papi:legendcraft_* element does when the jar and this config disagree.
"""

from pathlib import Path
import re
import unittest

import generate_hud as hud


REPO_ROOT = Path(__file__).resolve().parents[1]
LAYOUT_PATH = REPO_ROOT / "hud/betterhud/layouts/legendcraft-stat.yml"
IMAGES_PATH = REPO_ROOT / "hud/betterhud/images/legendcraft-stat.yml"
MANIFEST_PATH = REPO_ROOT / "hud/betterhud/hud-placeholders.txt"
EXPECTED_SKILL_ROW_Y_PX = -35
EXPECTED_FEEDBACK_LINE_Y_PX = -47
VANILLA_ITEM_NAME_OFFSET_PX = 59
EXPECTED_NATIVE_CLEARANCE_PX = 5
REQUIRED_CONTRACT_IDS = {"shield_current", "shield_max"}
# The three parts of the air element, and the built-in comparison that gates all three.
AIR_ELEMENT_NAMES = ("lc_air_empty", "lc_fill_air", "lc_icon_air")
AIR_GATE_FIRST, AIR_GATE_SECOND, AIR_GATE_OP = "air", "max_air", "<"


def layout_blocks(layout, name):
    return re.findall(
        rf"(?ms)^    \d+:\n      name: {re.escape(name)}\n.*?(?=^    \d+:|\Z)",
        layout,
    )


def generated_manifest_text():
    found = set(REQUIRED_CONTRACT_IDS)
    betterhud = REPO_ROOT / "hud/betterhud"
    for subdir in ("images", "layouts", "huds", "texts"):
        for path in (betterhud / subdir).glob("*.yml"):
            body = "\n".join(
                line
                for line in path.read_text(encoding="utf-8").splitlines()
                if not line.lstrip().startswith("#")
            )
            found.update(re.findall(r"papi:legendcraft_([a-z0-9_]+)", body))
    lines = [
        "# GENERATED by generate_hud.py -- the plugin<->HUD placeholder contract.",
        "# Every id here must be answered by LegendCraft-Classes HudPlaceholders",
        "# (enforced by HudPlaceholderContractTest). One `legendcraft_<id>` per line.",
        *(f"legendcraft_{placeholder_id}" for placeholder_id in sorted(found)),
    ]
    return "\n".join(lines) + "\n"


class HudlineGeometryTest(unittest.TestCase):

    def test_each_generated_row_has_the_ruled_y_and_its_own_slot_count_gate(self):
        frames = layout_blocks(hud._bh_stat_layout_yml(), "lc_skill_frame")
        self.assertEqual(7, len(frames), "one three-slot row plus one four-slot row")
        self.assertEqual(
            {str(EXPECTED_SKILL_ROW_Y_PX)},
            {re.search(r"^      y: (-?\d+)$", block, re.MULTILINE).group(1) for block in frames},
        )
        gates = [
            re.search(r'^          second: "\'(3|4)\'"$', block, re.MULTILINE).group(1)
            for block in frames
        ]
        self.assertEqual(3, gates.count("3"))
        self.assertEqual(4, gates.count("4"))

    def test_feedback_is_one_centered_line_above_the_rows(self):
        layout = hud._bh_stat_layout_yml()
        feedback = re.findall(
            r'(?ms)^    \d+:\n      name: lc_stat_text\n'
            r'      pattern: "<white>\[papi:legendcraft_feedback_line\]"\n'
            r'.*?(?=^    \d+:|\Z)',
            layout,
        )
        self.assertEqual(1, len(feedback), "one painted feedback line owns all three senders")
        self.assertIn("      align: center\n", feedback[0])
        self.assertIn("      scale: 0.5\n", feedback[0])
        self.assertIn(f"      y: {EXPECTED_FEEDBACK_LINE_Y_PX}\n", feedback[0])

    def test_native_item_lane_keeps_the_ruled_clear_gap_below_the_tiles(self):
        frames = layout_blocks(hud._bh_stat_layout_yml(), "lc_skill_frame")
        row_y_px = int(re.search(r"^      y: (-?\d+)$", frames[0], re.MULTILINE).group(1))
        row_bottom_from_screen_bottom_px = -(
            hud.STAT_HUD_Y + row_y_px + hud.SKILL_TILE
        )
        self.assertEqual(
            EXPECTED_NATIVE_CLEARANCE_PX,
            row_bottom_from_screen_bottom_px - VANILLA_ITEM_NAME_OFFSET_PX,
        )

    def test_checked_in_layout_and_manifest_equal_generator_truth(self):
        self.assertEqual(
            hud._bh_stat_layout_yml() + "\n",
            LAYOUT_PATH.read_text(encoding="utf-8"),
        )
        self.assertEqual(
            generated_manifest_text(),
            MANIFEST_PATH.read_text(encoding="utf-8"),
        )


class AirElementTest(unittest.TestCase):
    """HUD-AIR: the drowning read PR #7 took away, paid back inside the stat block."""

    def setUp(self):
        self.layout = hud._bh_stat_layout_yml()
        self.images = hud._bh_stat_images_yml()

    def air_blocks(self):
        blocks = {}
        for name in AIR_ELEMENT_NAMES:
            found = layout_blocks(self.layout, name)
            self.assertEqual(1, len(found), "%s should be exactly one element" % name)
            blocks[name] = found[0]
        return blocks

    def element_xy(self, block):
        return (int(re.search(r"^      x: (-?\d+)$", block, re.MULTILINE).group(1)),
                int(re.search(r"^      y: (-?\d+)$", block, re.MULTILINE).group(1)))

    def test_every_part_of_the_air_element_is_hidden_at_full_air(self):
        for name, block in self.air_blocks().items():
            self.assertIn("      conditions:\n", block, "%s draws ungated" % name)
            self.assertIn("          first: %s\n" % AIR_GATE_FIRST, block, name)
            self.assertIn("          second: %s\n" % AIR_GATE_SECOND, block, name)
            self.assertIn("          operation: '%s'\n" % AIR_GATE_OP, block, name)

    def test_the_air_element_rides_the_xp_row_inside_its_left_third(self):
        xpy = 2 * hud.BAR_H + hud.STAT_BAR_VGAP + hud.STAT_ROW_GAP
        xpx = hud.STAT_IW + hud.STAT_ICON_GAP
        blocks = self.air_blocks()

        channel = self.element_xy(blocks["lc_air_empty"])
        self.assertEqual((xpx, xpy), channel,
                         "the channel sits on the XP row, at the XP bar's left end")
        self.assertLessEqual(channel[0] + hud.AIR_W, xpx + hud.XP_W // 3,
                             "the bar must clear the centred level numeral")
        self.assertEqual((xpx + hud.BAR_PAD, xpy + hud.BAR_PAD),
                         self.element_xy(blocks["lc_fill_air"]))
        icon = self.element_xy(blocks["lc_icon_air"])
        self.assertEqual(0, icon[0], "the icon takes the XP row's empty left icon column")
        self.assertEqual(xpy + (hud.XP_H - hud.AIR_ICON_H) // 2, icon[1])

    def test_the_fill_is_betterhuds_native_air_listener(self):
        entry = re.search(r"(?ms)^lc_fill_air:\n(?:[ \t].*\n|\n)*", self.images)
        self.assertIsNotNone(entry, "lc_fill_air is not registered")
        body = entry.group(0)
        self.assertIn("  type: listener\n", body)
        self.assertIn("      class: air\n", body)

    def test_no_part_of_the_air_element_reads_a_placeholder_the_plugin_serves(self):
        for name, block in self.air_blocks().items():
            self.assertNotIn("papi:", block, "%s reaches PlaceholderAPI" % name)
        entry = re.search(r"(?ms)^lc_fill_air:\n(?:[ \t].*\n|\n)*", self.images)
        self.assertNotIn("papi:", entry.group(0))


class AirArtTest(unittest.TestCase):
    """The three PNGs the element points at exist, at the sizes the layout offsets assume."""

    def test_the_air_art_is_written_at_the_ruled_sizes(self):
        from PIL import Image
        for name, size in (
            ("bars/air_empty.png", (hud.AIR_W, hud.XP_H)),
            ("bars/fill_air.png", (hud.AIR_W - 2 * hud.BAR_PAD, hud.XP_H - 2 * hud.BAR_PAD)),
            ("stat-icons/air.png", (hud.AIR_ICON_H, hud.AIR_ICON_H)),
        ):
            path = REPO_ROOT / "hud" / name
            self.assertTrue(path.is_file(), "%s was never written" % name)
            with Image.open(path) as art:
                self.assertEqual(size, art.size, name)


if __name__ == "__main__":
    unittest.main()
