"""HUD generator acceptance suite for HUDLINE.

Run from the repository root:
    python tools/test_generate_hud.py

Acceptance criteria:
1. Both generated ability rows sit at y=-45; exactly three frames are gated to slot_count 3
   and exactly four are gated to slot_count 4.
2. One centered feedback text element reads legendcraft_feedback_line at y=-57 and scale 0.5.
3. The tile bottom stays 15px above the vanilla held-item-name lane used by the compositor.
4. Checked-in layout YAML and the cross-repo placeholder manifest equal generator truth.

First RED (2026-08-30, before generator implementation): four tests ran and all four failed.
The checked-in manifest differed because shield_current/shield_max were absent; generated frame
y values were {-25}, expected {-45}; the feedback element count was 0, expected 1; and native-lane
clearance was -5px, expected 15px.
"""

from pathlib import Path
import re
import unittest

import generate_hud as hud


REPO_ROOT = Path(__file__).resolve().parents[1]
LAYOUT_PATH = REPO_ROOT / "hud/betterhud/layouts/legendcraft-stat.yml"
MANIFEST_PATH = REPO_ROOT / "hud/betterhud/hud-placeholders.txt"
EXPECTED_SKILL_ROW_Y_PX = -45
EXPECTED_FEEDBACK_LINE_Y_PX = -57
VANILLA_ITEM_NAME_OFFSET_PX = 59
EXPECTED_NATIVE_CLEARANCE_PX = 15
REQUIRED_CONTRACT_IDS = {"shield_current", "shield_max"}


def layout_blocks(layout, name):
    return re.findall(
        rf"(?ms)^    \d+:\n      name: {re.escape(name)}\n.*?(?=^    \d+:|\Z)",
        layout,
    )


def generated_manifest_text():
    found = set(REQUIRED_CONTRACT_IDS)
    betterhud = REPO_ROOT / "hud/betterhud"
    for subdir in ("images", "layouts", "huds", "texts"):
        for path in (betterhud / subdir).glob("*.yml"):
            body = "\n".join(
                line
                for line in path.read_text(encoding="utf-8").splitlines()
                if not line.lstrip().startswith("#")
            )
            found.update(re.findall(r"papi:legendcraft_([a-z0-9_]+)", body))
    lines = [
        "# GENERATED by generate_hud.py -- the plugin<->HUD placeholder contract.",
        "# Every id here must be answered by LegendCraft-Classes HudPlaceholders",
        "# (enforced by HudPlaceholderContractTest). One `legendcraft_<id>` per line.",
        *(f"legendcraft_{placeholder_id}" for placeholder_id in sorted(found)),
    ]
    return "\n".join(lines) + "\n"


class HudlineGeometryTest(unittest.TestCase):

    def test_each_generated_row_has_the_ruled_y_and_its_own_slot_count_gate(self):
        frames = layout_blocks(hud._bh_stat_layout_yml(), "lc_skill_frame")
        self.assertEqual(7, len(frames), "one three-slot row plus one four-slot row")
        self.assertEqual(
            {str(EXPECTED_SKILL_ROW_Y_PX)},
            {re.search(r"^      y: (-?\d+)$", block, re.MULTILINE).group(1) for block in frames},
        )
        gates = [
            re.search(r'^          second: "\'(3|4)\'"$', block, re.MULTILINE).group(1)
            for block in frames
        ]
        self.assertEqual(3, gates.count("3"))
        self.assertEqual(4, gates.count("4"))

    def test_feedback_is_one_centered_line_above_the_rows(self):
        layout = hud._bh_stat_layout_yml()
        feedback = re.findall(
            r'(?ms)^    \d+:\n      name: lc_stat_text\n'
            r'      pattern: "<white>\[papi:legendcraft_feedback_line\]"\n'
            r'.*?(?=^    \d+:|\Z)',
            layout,
        )
        self.assertEqual(1, len(feedback), "one painted feedback line owns all three senders")
        self.assertIn("      align: center\n", feedback[0])
        self.assertIn("      scale: 0.5\n", feedback[0])
        self.assertIn(f"      y: {EXPECTED_FEEDBACK_LINE_Y_PX}\n", feedback[0])

    def test_native_item_lane_keeps_the_ruled_clear_gap_below_the_tiles(self):
        frames = layout_blocks(hud._bh_stat_layout_yml(), "lc_skill_frame")
        row_y_px = int(re.search(r"^      y: (-?\d+)$", frames[0], re.MULTILINE).group(1))
        row_bottom_from_screen_bottom_px = -(
            hud.STAT_HUD_Y + row_y_px + hud.SKILL_TILE
        )
        self.assertEqual(
            EXPECTED_NATIVE_CLEARANCE_PX,
            row_bottom_from_screen_bottom_px - VANILLA_ITEM_NAME_OFFSET_PX,
        )

    def test_checked_in_layout_and_manifest_equal_generator_truth(self):
        self.assertEqual(
            hud._bh_stat_layout_yml() + "\n",
            LAYOUT_PATH.read_text(encoding="utf-8"),
        )
        self.assertEqual(
            generated_manifest_text(),
            MANIFEST_PATH.read_text(encoding="utf-8"),
        )


if __name__ == "__main__":
    unittest.main()
